name: 'main'

on:
  pull_request:
  push:
    branches:
      - '**'

env:
  GITHUB_SERVICE_USER: "rajsite"
  GITHUB_SERVICE_EMAIL: "rajsite@users.noreply.github.com"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          # Required for beachball changelog detection
          fetch-depth: 0
          # Must checkout with a token that can push to protected branches for beachball
          # Cannot rely on GITHUB_TOKEN with workflow contents permission
          # See: https://github.com/orgs/community/discussions/40971
          token: ${{ secrets.GITHUBPAGESDEPLOYTOKEN }}

      # Install dependencies
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - run: npm ci

      - name: Log
        run: |
          echo GITHUB_EVENT_NAME $GITHUB_EVENT_NAME
          echo GITHUB_REF $GITHUB_REF
          echo GITHUB_BASE_REF $GITHUB_BASE_REF
          echo GITHUB_HEAD_REF $GITHUB_HEAD_REF
          echo GITHUB_EVENT_REF $GITHUB_EVENT_REF
      
      - name: Log IF event_name pull_request
        if: github.event_name == 'pull_request'
        run: echo It is a PR

      - name: Log IF startsWith matches when it shouldn't
        if: startsWith('refs/pull/957/merge', 'refs/heads/renovate/')
        run: echo startsWith makes no sense

      - name: Log IF ref renovate branch 
        if: startsWith(github.ref, 'refs/heads/renovate/')
        run: echo ref is a Renovate branch $GITHUB_REF

      - name: Log IF baseref renovate branch 
        if: startsWith(github.base_ref, 'refs/heads/renovate/')
        run: echo baseref is a Renovate branch $GITHUB_BASE_REF

      - name: Log IF headref renovate branch 
        if: startsWith(github.head_ref, 'renovate/')
        run: echo head is a Renovate branch $GITHUB_HEAD_REF

      - name: Log IF event ref renovate branch 
        if: startsWith(github.event.ref, 'refs/heads/renovate/')
        run: echo event ref is a Renovate branch $GITHUB_EVENT_REF

      - name: Log IF both 
        if: github.event_name == 'pull_request' && startsWith(github.head_ref, 'renovate/')
        run: echo It is both          


      # Audit
      - run: npm audit --only=prod
      # https://github.com/ni/nimble/issues/801
      # - run: npm audit --audit-level=critical

      # Build
      - run: npm run build

      # Pack
      - run: npm run pack
      - uses: actions/upload-artifact@v3
        with:
          name: packages
          path: |
            packages/**/*.tgz
            packages/**/*.nupkg
            angular-workspace/**/*.tgz
          if-no-files-found: error
      # The actions/upload-pages-artifact@v1 results in unexpected warning messages, workaround for:
      # https://github.com/actions/upload-pages-artifact/issues/45
      - name: Pages file permission workaround
        run: chmod -c -R +rX packages/site/dist
      - uses: actions/upload-pages-artifact@v1
        with:
          path: 'packages/site/dist'

      # Publish to Chromatic (from any push)
      - name: Publish to Chromatic
        if: github.event_name == 'push'
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: ./packages/nimble-components
          storybookBuildDir: ../../packages/site/dist/storybook
          exitOnceUploaded: true # Do not wait for test results
          exitZeroOnChanges: true # Option to prevent the workflow from failing

      # Lint
      - run: npm run lint

      # Test
      - run: npm run test

      # Run Lighthouse audit (from any push)
      - name: Performance Audit with Lighthouse CI
        if: github.event_name == 'push'
        run: npm run performance
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      # Generate change file for Renovate PRs
      - name: Generate change file for Renovate PRs
        if: github.event_name == 'pull_request' && startsWith(github.head_ref, 'renovate/')
        run: |
          echo Creating change file for Renovate PR in branch "${{ env.GITHUB_HEAD_REF }}"
          npm run change:deps
          git status
          git push
          git status

      # Check for change file
      - run: npm run check

      - name: Validate no changes to tracked files
        run: |
          echo print files with changes:
          git diff-index --ignore-space-at-eol --stat HEAD
          echo exit with error if there are changes.
          git diff-index --quiet --ignore-space-at-eol --stat HEAD

      # Release
      - name: Set Git User
        if: startsWith(github.ref, 'refs/heads/main')
        run: |
          git config --global user.name "${{ env.GITHUB_SERVICE_USER }}"
          git config --global user.email "${{ env.GITHUB_SERVICE_EMAIL }}"

      # Update package versions, tag, and publish to npm (only from main)
      - name: Beachball publish
        if: startsWith(github.ref, 'refs/heads/main')
        env:
          NPM_SECRET_TOKEN: ${{ secrets.NPM_TOKEN }}
          NUGET_SECRET_TOKEN: ${{ secrets.NUGET_TOKEN }}
        run: npm run invoke-publish

  pages:
    needs: build
    if: startsWith(github.ref, 'refs/heads/main')
    runs-on: ubuntu-22.04
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
